# Generated by Django 5.2.5 on 2025-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_nftcard_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.AddField(
            model_name='nftcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nftcards/'),
        ),
    ]
