# Generated by Django 5.2.5 on 2025-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_color_image_nftcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7, verbose_name='HEX code'),
        ),
    ]
