# Generated by Django 5.2.5 on 2025-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_collection_nftcard_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftcard',
            name='genre',
        ),
        migrations.AddField(
            model_name='nftcard',
            name='genre',
            field=models.ManyToManyField(blank=True, to='myapp.genre'),
        ),
    ]
