# Generated by Django 5.2.5 on 2026-03-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_listing_highest_bid_alter_bid_amount_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcard',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nftcards', to='myapp.collection'),
        ),
    ]
